### ISSUE TITLE
[FEAT] 친해지기 디테일 보충

### ISSUE THREAD

**Issue by unam98** [depromeet/TeumTeum-Android#100]
## 💡 Issue

친해지기 디테일 보충
## 📝 todo

- [x] 위치기반/ 체크한 캐릭터가 있을 시에만 버튼 활성화
- [x] 위치기반/체크 drawable 색상 다크/라이트 적용
- [x] 앱바 백버튼 리스너 설정
- [x] 온보딩 이미지 수정
- [x] 바인딩되는 star 이미지 수정
- [ ] 소개서 뒤집기 애니메이션 구현 
- [ ] 종료 팝업 띄우기
- [ ] 흔들기 팝업 띄우기
- [ ] 백스택 처리
