### ISSUE TITLE
[FIX] 온보딩/회원가입 1차 QA 대응

### ISSUE THREAD

**Issue by blueme0** [depromeet/TeumTeum-Android#103]
## 💡 Issue

온보딩/회원가입 1차 QA 대응

## 📝 todo

- [x] [ONB] 좌우 마진 20px 통일!
- [x] [SIG_02]  폰트 설정 이슈
- [x] [SIG_14] 카드 수정 화면 - '수정 아이콘'만 넘어가는데 텍스트 클릭해도 수정으로 잘 넘어가게 수정 요망
- [x] [SIG_14_01_00] 소개서 수정 클릭 시 수정 완료 CTA가 디폴트가 되도록 변경
- [x] [SIG] 회원가입 단계에서 텍스트 입력받을 때 줄바꿈 막기
- [x] [SIG_11_01_00] chip 마진, 패딩 수정
- 아래 사항들은 디자인단의 우선 수정 필요
- [x] [SIG_02] 약관 html title 크기 수정
- [ ] [SIG_08_01_00] title과 contents의 margin 간격 이슈(디자인단)
- [x] [ONB] 글씨 headline 2 크게 느껴짐
