### ISSUE TITLE
[FIX] 1차 QA 피드백 적용

### ISSUE THREAD

**Issue by Mnseo** [depromeet/TeumTeum-Android#104]
## 💡 Issue
모임생성 / 마이페이지 1차 QA 피드백 적

## 📝 todo

- [x] TEUM1-36 / 내 정보 수정 Chip 디자인 수정 
- [x] TEUM1-30 / 모임 상세 페이지가 썸네일 화면에 Width가 full로 되어있어야함
- [x] TEUM1-23 / 자기계발/관심 분야에서 칩 위아래 마진이 다름 
- [x] DET_01 / 참여할래요 버튼 하단 고정 필요 
- [x] DET_01 / 모임 다 만들고 다음 버튼을 누르면 모임 생성에 오류가 생겼습니다라고 뜨고 안됨 
- [x] CLB_04 / 시간 넣을때 4개로 제한 
- [x] 다크/라이트 모드 설정
