### ISSUE TITLE
[FIX] 최종 배포 전 오류 수정 

### ISSUE THREAD

**Issue by Mnseo** [depromeet/TeumTeum-Android#118]
## 💡 Issue
배포 전 오류 확인 및 수정 

## 📝 todo

- [x] 내 카드 수정 interest Intent 데이터 수정
- [x] navigation animation 추가 
- [x] 카드 앞 / 뒷면 오류 확인
