### ISSUE TITLE
[FIX] 친해지기 런칭데이 QA 

### ISSUE THREAD

**Issue by unam98** [depromeet/TeumTeum-Android#131]
## 💡 Issue

- 친해지기 버그 수정
## 📝 todo

- [x] 100m 이내 유저 리스트 중복 제거 (같은 유저가 2번씩 뜨는 문제 - 클라 방어 로직)
- [x] 로그아웃, 회원탈퇴, 토큰 만료 시 SP clear (이전 유저 정보가 떴던 문제)
- [x] SP -> datastore
- [x] 흔들기 안내 모달을 별도의 페이지가 아닌 기존 페이지 위에 띄울 것 (Dialog 유틸 추가)
- [x] 소개서 "GOAL" textColor 캐릭터 컬러와 일치시키기 (추후 커스텀뷰 안에 내장시킬 예정)
- [x] 커스텀 카드 뒷면 item 간격 수정
- [x] 커스텀 카드 뒷면 isModify, isModifyDetail 추가
- [x] 커스텀 카드뷰 기본값 제거 
- [x] 커스텀 카드 뒷면 관심사 삭제 기능 구현
- [x] 커스텀 카드뷰 뒷면 관심사 추가 시 접두어 # 추가
