### ISSUE TITLE
[FEAT] 알림 화면 연결

### ISSUE THREAD

**Issue by blueme0** [depromeet/TeumTeum-Android#133]
## 💡 Issue

알림 화면 연결

## 📝 todo

- [x] 홈 - 알림 리스트 화면 연결
- [x] 알림 리스트 서버 연결
- [x] 마이페이지 - 푸시 알림 on/off 적용 (DataStore)
- [x] 알림 type 별로 화면 연결
