### ISSUE TITLE
[FIX] 카드 뒷면 관심사 삭제 디테일 보충

### ISSUE THREAD

**Issue by unam98** [depromeet/TeumTeum-Android#138]
## 📝 todo

- [x] 선택 가능한 관심사 최대 3개로 제한
- [x] 1개 이하 삭제 제한 토스트 메세지 수정
- [x] 삭제, 추가 시 itemDecoration 충돌 나면서 간격 이상해지는 거 해결
- [x] data 추가 시 기존 data가 안 날아가고 쌓일 수 있게 하기
