### ISSUE TITLE
[FIX] 2차 QA 수정사항 반영

### ISSUE THREAD

**Issue by blueme0** [depromeet/TeumTeum-Android#160]
## 💡 Issue

2차 QA 수정사항 반영

## 📝 todo

- [x] 회원가입 : 기본정보 입력 - 이름 input error case 추가
- [ ] 회원가입 : 예시 소개서 내 text 수정
- [x] 알림 수신 수정
