### ISSUE TITLE
[FEAT] 친해지기 / 흔들 때 진동 구현

### ISSUE THREAD

**Issue by unam98** [depromeet/TeumTeum-Android#18]
## 💡 Issue

- 흔들 때 진동 구현 
## 📝 todo

- [x] 커스텀 진동 패턴 구현 
- [x] 흔들기 감지 코드 세팅
- [x] 흔들 때 진동 울리도록 연결
