### ISSUE TITLE
[FEAT] 회원가입 UI 구현

### ISSUE THREAD

**Issue by blueme0** [depromeet/TeumTeum-Android#27]
## 💡 Issue
회원가입 UI 구현

## 📝 todo

- [x] 회원가입 시작 화면 UI 구현
- [x] 약관 동의 UI 구현
- [x] 소개서 인트로 UI 구현
- [x] 캐릭터 선택 UI 구현
- [x] 위치 허용
