### ISSUE TITLE
[FEAT] 모임 참여 확인 & 완료 구현

### ISSUE THREAD

**Issue by kkk5474096** [depromeet/TeumTeum-Android#32]
## 💡 Issue
모임 참여 확인 & 완료 화면, 기능 구현

## 📝 todo

- [ ] 모임 참여 확인 UI 작업
- [ ] 모임 참여 확인 기능 구현
- [ ] 모임 참여 완료 UI 작업
- [ ] 모임 참여 완료 기능 구현
