### ISSUE TITLE
[FEAT] 모임탐색 UI 구현

### ISSUE THREAD

**Issue by kkk5474096** [depromeet/TeumTeum-Android#5]
## 💡 Issue
- 모임탐색 UI 구현

## 📝 todo
- [x] 모임탐색 Activity Layout 구현
- [x] 모임 리스트 아이템 Layout 구현
- [x] 모임 리스트 어뎁터 구현
