### ISSUE TITLE
[FEAT] 홈 메인화면 전체 구현

### ISSUE THREAD

**Issue by kkk5474096** [depromeet/TeumTeum-Android#52]
## 💡 Issue
홈 메인화면 전체 구현

## 📝 todo

- [ ] 홈 메인화면 UI 구현
- [ ] 홈 메인화면 기능 구현
- [ ] 홈 메인화면 서버 연결
