### ISSUE TITLE
[FIX] 코멘트 반영

### ISSUE THREAD

**Issue by blueme0** [depromeet/TeumTeum-Android#62]
## 💡 Issue

코멘트 반영

## 📝 todo

- [x] 인트로 화면에 splash 바로 뜨게끔 수정
- [x] 커서 색상 변경
- [x] 토큰 지우고 저장된 유저 정보 지우고 isLogin 비활성화 -> 로그아웃
- [x] 소셜 로그인 시 쿠키 지우기 (다른 카카오 계정으로도 로그인 가능하도록)
