### ISSUE TITLE
[FEAT] 모임 상세조회 구현

### ISSUE THREAD

**Issue by kkk5474096** [depromeet/TeumTeum-Android#72]
## 💡 Issue
[FEAT] 모임 상세조회 구현

## 📝 todo

- [x] 기존 모임 조회 Compose 뷰 수정 필요
- [x] 기존 로직에 영향 안가게 분기처리
- [x] 참여 신청까지 구현
