### ISSUE TITLE
[FEAT] 모임 참여중인 사용자 카드 구현 & 강민 1차 Sprint 개발 완료

### ISSUE THREAD

**Issue by kkk5474096** [depromeet/TeumTeum-Android#83]
## 💡 Issue
모임 참여중인 사용자 리스트 카드 구현

## 📝 todo

- [x] viewpager로 사용자 리스트 구현
- [x] 다음 사용자 리스트 영역 보이도록 추가 구현
- [x] viewPager 아래 indicator 구현
- [x] 클릭 시 소개서로 이동
- [x] 화면 이동간 애니메이션 추가
- [x] 1차 개발 완료
