### ISSUE TITLE
[FEAT] 뒤로가기 콜백 및 마무리 작업

### ISSUE THREAD

**Issue by blueme0** [depromeet/TeumTeum-Android#85]
## 💡 Issue

뒤로가기 콜백 및 마무리 작업

## 📝 todo

- [x] 뒤로가기 콜백 적용
- [x] 화면 이동 애니메이션 적용
- [x] 카드 후면 연결
